### ISSUE TITLE
Colour background

### ISSUE THREAD

**Issue by ntoand** [OKaluza/sharevol#2]
When I click export, I can see
"properties": {
    "nogui": false,
    "background": "rgba(0,0,0,0.00)"
  },
exported background colour is not as same as that in the interface.

**Comment by OKaluza** [comment]
Hi Toan, I can't seem to duplicate this. Using http://okaluza.github.io/sharevol/ I can modify the background with the colourmap settings and press export and it is correct, can you give me the exact steps to duplicate the issue?

**Comment by OKaluza** [comment]
Unless you mean the page background is showing through? Because if the background colour alpha is 0 it will just show the off-white page background colour.
There is a slider to adjust the transparency on the colour picker if you want a non-transparent background colour.

**Comment by ntoand** [comment]
Hi Owen,

I set
"properties": {
    "nogui": false,
    "background": "rgba(0,0,0,1.00)"
  },
in json file. However, when I run sharevol and export, the values become
"properties": {
    "nogui": false,
    "background": "rgba(0,0,0,0.00)"
  },
and I cannot see black background in sharevol.

And it seems that the lowPowerDevice is not exported.

**Comment by OKaluza** [comment]
This is fixed now 7557c7f19484fcdf58a0c1e78ecf3ad422ffaf96
The lowPowerDevice setting was not intended to be exported, any reason you want it to be?
